"use strict";
try {
    let x = 10;
    //miFincion();

} catch (error) {
    console.log(error);
} finally {
    console.log('Termina la revisi√≥n de errores');
}

console.log('Continuamos...');